name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      
      # Install dependencies
      - name: Install quasar
        run: npm install -g @quasar/cli

      # Install dependencies
      - name: Install dependencies
        run: yarn install
      
      # Build application
      - name: Build with quasar
        run: quasar build
      
      # Deploy built application to GitHub pages branch
      - name: Deploy to GitHub Pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout --orphan gh-pages
          git --work-tree dist/spa add --all
          git --work-tree dist/spa commit -m 'Deploy'
          git push origin HEAD:gh-pages --force
          quasar clean
          git checkout -f main
          git branch -D gh-pages